"""empty message

Revision ID: 51cdd26bdf4b
Revises: 
Create Date: 2020-03-19 18:38:54.041087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cdd26bdf4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teste',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teste')
    # ### end Alembic commands ###
