"""empty message

Revision ID: 67f1f9746458
Revises: 
Create Date: 2020-03-20 18:51:44.758770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f1f9746458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Channels',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Players',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Clubs',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Player_Id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['Player_Id'], ['Players.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Subs',
    sa.Column('User_Id', sa.BigInteger(), nullable=True),
    sa.Column('Channel_Id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['Channel_Id'], ['Channels.Id'], ),
    sa.ForeignKeyConstraint(['User_Id'], ['Players.Id'], )
    )
    op.create_table('Wallets',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Player_Id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['Player_Id'], ['Players.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Player_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Wallets')
    op.drop_table('Subs')
    op.drop_table('Clubs')
    op.drop_table('Players')
    op.drop_table('Channels')
    # ### end Alembic commands ###
