"""empty message

Revision ID: 8831e2887777
Revises: e145191da27b
Create Date: 2020-03-20 16:34:15.106308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '8831e2887777'
down_revision = 'e145191da27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clubs', 'player_id', new_column_name='Player_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clubs', 'Player_id', new_column_name='player_id')
    # ### end Alembic commands ###
