"""empty message

Revision ID: aeacf79231f4
Revises: 8831e2887777
Create Date: 2020-03-20 16:40:21.240456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'aeacf79231f4'
down_revision = '8831e2887777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clubs','Player_id', new_column_name='Player_Id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clubs','Player_Id', new_column_name='Player_id')
    # ### end Alembic commands ###
