"""empty message

Revision ID: d46bad82d260
Revises: 6616e1494606
Create Date: 2020-04-17 19:37:27.355930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46bad82d260'
down_revision = '6616e1494606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Logs',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Message', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Logs')
    # ### end Alembic commands ###
