"""empty message

Revision ID: e145191da27b
Revises: 
Create Date: 2020-03-20 16:20:05.249532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e145191da27b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Players',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Clubs',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['Players.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clubs')
    op.drop_table('Players')
    # ### end Alembic commands ###
